<?php

namespace ContainerHHu5sj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UnvDGkIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.unvDGkI' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.unvDGkI'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'r' => ['privates', 'App\\Repository\\HistoryRepository', 'getHistoryRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\QuizRepository', 'getQuizRepositoryService', true],
            'session' => ['services', 'session', 'getSessionService', false],
        ], [
            'r' => 'App\\Repository\\HistoryRepository',
            'repo' => 'App\\Repository\\QuizRepository',
            'session' => '?',
        ]);
    }
}
