<?php

namespace ContainerHHu5sj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreationquizzTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\CreationquizzType' shared autowired service.
     *
     * @return \App\Form\CreationquizzType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/CreationquizzType.php';

        return $container->privates['App\\Form\\CreationquizzType'] = new \App\Form\CreationquizzType();
    }
}
