<?php

namespace ContainerHHu5sj6;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreatequizzFormTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\Type\CreatequizzFormType' shared autowired service.
     *
     * @return \App\Form\Type\CreatequizzFormType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/form/AbstractType.php';
        include_once \dirname(__DIR__, 4).'/src/Form/Type/CreatequizzFormType.php';

        return $container->privates['App\\Form\\Type\\CreatequizzFormType'] = new \App\Form\Type\CreatequizzFormType();
    }
}
