<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHHu5sj6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHHu5sj6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHHu5sj6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHHu5sj6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHHu5sj6\App_KernelDevDebugContainer([
    'container.build_hash' => 'HHu5sj6',
    'container.build_id' => 'e8c1d7c9',
    'container.build_time' => 1627044875,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHHu5sj6');
