<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'admin' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
    'admin_index' => [[], ['_controller' => 'App\\Controller\\AdminController::index'], [], [['text', '/admin/admin']], [], []],
    'admin_utilisateurs' => [[], ['_controller' => 'App\\Controller\\AdminController::usersList'], [], [['text', '/admin/utilisateurs']], [], []],
    'admin_modifier_utilisateur' => [['id'], ['_controller' => 'App\\Controller\\AdminController::editUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/admin/utilisateurs/modifier']], [], []],
    'categorie_show' => [['id'], ['_controller' => 'App\\Controller\\CategorieController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categorie']], [], []],
    'result' => [[], ['_controller' => 'App\\Controller\\CategorieController::result'], [], [['text', '/result']], [], []],
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
    'test' => [[], ['_controller' => 'App\\Controller\\TestController::start'], [], [['text', '/test']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\LoginController::index'], [], [['text', '/login']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\HomeController::index'], [], [['text', '/']], [], []],
    'account' => [[], ['_controller' => 'App\\Controller\\AccountController::index'], [], [['text', '/account']], [], []],
    'categorie' => [['id'], ['_controller' => 'App\\Controller\\Catego::index'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/categorie']], [], []],
    'categorieresult' => [['id'], ['_controller' => 'App\\Controller\\Catego::index'], [], [['text', '/result'], ['variable', '/', '[^/]++', 'id', true], ['text', '/categorie']], [], []],
    'createquizz' => [[], ['_controller' => 'App\\Controller\\CreatequizzController::index'], [], [['text', '/createquizz']], [], []],
    'createquizz2' => [[], ['_controller' => 'App\\Controller\\Createquizz2Controller::index'], [], [['text', '/createquizz2']], [], []],
    'dashboard' => [[], ['_controller' => 'App\\Controller\\Admin\\DashboardController::index'], [], [['text', '/admin']], [], []],
];
